GestionEvenement/urls.py
from django.contrib import admin
from django.urls import path, include
from .views import index, registration_view,faq,about,contact
urlpatterns = [
    path('admin/', admin.site.urls),
   
    path("accounts/", include("django.contrib.auth.urls")),
    path("", index, name="index"),
    path("accounts/register/", registration_view, name="register"),
    path('faq/', faq, name='faq'),
    path('about/', about, name='about'),
    
    path('contact/', contact, name='contact'),
        path('module/', include('film.urls')),
]

film/urls.py
from django.urls import path,include
from .views import (
    PersonnageListView,
    PersonnageDetailView,
    PersonnageCreateView,
    PersonnageUpdateView,
    PersonnageDeleteView,
      scenarioListView,
    scenarioDetailView,
    scenarioCreateView,
    scenarioUpdateView,
    scenarioDeleteView,
        ProjetListView,
    ProjetDetailView,
    ProjetCreateView,
    ProjetUpdateView,
    ProjetDeleteView,
    EffetSonoreVisuellesListView,
    EffetSonoreVisuellesDetailView,
    EffetSonoreVisuellesCreateView,
    EffetSonoreVisuellesUpdateView,
    EffetSonoreVisuellesDeleteView,
    analyze_sentiment,
    sentiment_analysis_view,
    chat,  # Import the chat view
    ask_question, 
    like_personnage,
    generate_image_ajax,
    film_create,
    film_list,
    film_detail,
    film_update,
    film_delete,
    add_comment,
    delete_comment
)

app_name = 'module'

urlpatterns = [
    path('personnages/', PersonnageListView.as_view(), name='personnage_list'),
    path('personnages/<int:pk>/', PersonnageDetailView.as_view(), name='personnage_detail'),  # Correction ici
    path('personnages/nouveau/', PersonnageCreateView.as_view(), name='personnage_create'),
    path('personnages/<int:pk>/modifier/', PersonnageUpdateView.as_view(), name='personnage_update'),
    path('personnages/<int:pk>/supprimer/', PersonnageDeleteView.as_view(), name='personnage_delete'),
    path('personnages/<int:pk>/like/', like_personnage, name='like_personnage'),
    path('personnage/<int:personnage_id>/add_comment/', add_comment, name='add_comment'),
    path('comment/<int:comment_id>/delete/', delete_comment, name='delete_comment'),
    path('scenario/', scenarioListView.as_view(), name='scenario_list'),
    path('scenario/<int:pk>/', scenarioDetailView.as_view(), name='scenario_detail'),
    path('scenario/nouveau/', scenarioCreateView.as_view(), name='scenario_create'),
    path('scenario/<int:pk>/modifier/', scenarioUpdateView.as_view(), name='scenario_update'),
    path('scenario/<int:pk>/supprimer/', scenarioDeleteView.as_view(), name='scenario_delete'),
   path('chat/', chat, name='chat_bot'),  # URL for the chatbot interface
    path('ask/', ask_question, name='ask_question'), 
     path('generate-image/', generate_image_ajax, name='generate_image_ajax'),
       path('film/', film_list, name='film_list'),
    path('film/new/', film_create, name='film_create'),
    path('film/<int:pk>/', film_detail, name='film_detail'),
    path('film/<int:pk>/edit/', film_update, name='film_update'),
    path('film/<int:pk>/delete/',film_delete, name='film_delete'),
    path('projets/', ProjetListView.as_view(), name='projet_list'),
    path('projets/<int:pk>/', ProjetDetailView.as_view(), name='projet_detail'),
    path('projets/create/', ProjetCreateView.as_view(), name='projet_create'),
    path('projets/update/<int:pk>/', ProjetUpdateView.as_view(), name='projet_update'),
    path('projets/delete/<int:pk>/', ProjetDeleteView.as_view(), name='projet_delete'),
     path('effetsonorevisuelles/', EffetSonoreVisuellesListView.as_view(), name='effetsonorevisuelles_list'),
    path('effetsonorevisuelles/<int:pk>/', EffetSonoreVisuellesDetailView.as_view(), name='effetsonorevisuelles_detail'),
    path('effetsonorevisuelles/create/', EffetSonoreVisuellesCreateView.as_view(), name='effetsonorevisuelles_create'),
    path('effetsonorevisuelles/update/<int:pk>/', EffetSonoreVisuellesUpdateView.as_view(), name='effetsonorevisuelles_update'),
    path('effetsonorevisuelles/delete/<int:pk>/', EffetSonoreVisuellesDeleteView.as_view(), name='effetsonorevisuelles_delete'),
    path('sentimentBot/sentiment-analysis/', sentiment_analysis_view, name='sentiment_analysis'),
    
]

templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
  <meta charset="UTF-8" />
  <title>{% block title %}My Site{% endblock %}</title>
  <meta name="viewport" content="width=device-width,initial-scale=1" />
  


  <!-- Précharger les polices de Google -->
  <link rel="preconnect" href="https://fonts.googleapis.com">
  <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
  <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;300;400;700;900&display=swap" rel="stylesheet">
  {% load bootstrap5 %}
  {% bootstrap_css %}
  {% bootstrap_javascript %}
  <!-- CSS Local -->
  {% load static %}
  <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css">
  <link rel="stylesheet" href="{% static 'css/bootstrap.min.css' %}" >
  <link rel="stylesheet" href="{% static 'css/bootstrap-icons.css' %}" >
  <link rel="stylesheet" href="{% static 'css/slick.css' %}">
  <link rel="stylesheet" href="{% static 'css/tooplate-little-fashion.css' %}?{% now "U" %}">
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

</head>
<body>
  {% if user.is_authenticated %}
  <nav class="navbar navbar-expand-lg mb-5">
    <div class="container">
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <a class="navbar-brand" href="{% url 'index' %}">
            <strong><span>Script</span> Genie</strong>
        </a>

      

        <div class="collapse navbar-collapse" id="navbarNav">
            <ul class="navbar-nav mx-auto">
                <li class="nav-item">
                    <a class="nav-link active" href="{% url 'index' %}">Home</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'about' %}">Story</a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'module:scenario_list' %}">Scénario </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'module:personnage_list' %}"> Personnage </a>
                </li>

                <li class="nav-item">
                    <a class="nav-link" href="{% url 'module:projet_list' %}">Projet</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'module:effetsonorevisuelles_list' %}">Effet</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'module:sentiment_analysis' %}">sentiment analysis</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'faq' %}">idée </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'module:film_list' %}">Film</a>
                </li>
                <li class="nav-item">
                    <form action="{% url 'logout' %}" method="post" style="display:inline;">
                        {% csrf_token %}
                        <button type="submit" class="nav-link btn btn-link" style="padding: 0;">Logout</button>
                    </form>
                </li>
                <li class="nav-item">
                    <span class="nav-link">Welcome, {{ user.username }}</span>
                </li>
            </ul>
            
           
        </div>
    </div>
</nav>
{% else %}
<nav class="navbar navbar-expand-lg">
  <div class="container">
      <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
      </button>

      <a class="navbar-brand" href="{% url 'index' %}">
          <strong><span>Script</span> Genie</strong>
      </a>

    
      <div class="collapse navbar-collapse" id="navbarNav">
          <ul class="navbar-nav mx-auto">
              <li class="nav-item">
                  <a class="nav-link active" href="{% url 'index' %}">Home</a>
              </li>

              <li class="nav-item">
                  <a class="nav-link" href="{% url 'about' %}">about</a>
              </li>


              <li class="nav-item">
                  <a class="nav-link" href="{% url 'faq' %}"> faq </a>
              </li>

         
              <li class="nav-item">
               <a href="{% url 'register' %}">   <span class="nav-link" >register</span></a>
              </li>
          </ul>
      </div>
  </div>
</nav>

{% endif %}

<div class="container mt-5">
  {% block content %}{% endblock %}
</div>


  <!-- JavaScript Local -->
  <script src="{% static 'js/jquery.min.js' %}"></script>
  <script src="{% static 'js/bootstrap.bundle.min.js' %}"></script>
  <script src="{% static 'js/Headroom.js' %}"></script>
  <script src="{% static 'js/jQuery.headroom.js' %}"></script>
  <script src="{% static 'js/slick.min.js' %}"></script>
  <script src="{% static 'js/custom.js' %}"></script>
  <script src="https://cdn.jsdelivr.net/npm/chart.js"></script>

</body>
</html>

templates/contact.html
{% extends "base.html" %}

{% load static %}
{%block content%}
        <section class="preloader">
            <div class="spinner">
                <span class="sk-inner-circle"></span>
            </div>
        </section>
    
        <main>

            <nav class="navbar navbar-expand-lg">
                <div class="container">
                    <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNav" aria-controls="navbarNav" aria-expanded="false" aria-label="Toggle navigation">
                        <span class="navbar-toggler-icon"></span>
                    </button>

                    <a class="navbar-brand" href="index.html">
                        <strong><span>Script</span> Genie</strong>
                    </a>

                

                    <div class="collapse navbar-collapse" id="navbarNav">
                        <ul class="navbar-nav mx-auto">
                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'index' %}">Home</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'about' %}">About US</a>
                            </li>

                       

                            <li class="nav-item">
                                <a class="nav-link" href="{% url 'faq' %}">FAQs</a>
                            </li>

                            <li class="nav-item">
                                <a class="nav-link active" href="{% url 'contact' %}">Contact</a>
                            </li>
                        </ul>

                    </div>
                </div>
            </nav>

            <header class="site-header section-padding-img site-header-image">
                <div class="container">
                    <div class="row">

                        <div class="col-lg-10 col-12 header-info">
                            <h1>
                                <span class="d-block text-primary">Say hello to us</span>
                                <span class="d-block text-dark">love to hear you</span>
                            </h1>
                        </div>
                    </div>
                </div>

                <img src="{% static 'images/header/positive-european-woman-has-break-after-work.jpg' %}" class="header-image img-fluid" alt="">
            </header>

            <section class="contact section-padding">
                <div class="container">
                    <div class="row">
                        
                        <div class="col-lg-6 col-12">
                            <h2 class="mb-4">Let's <span>begin</span></h2>

                            <form class="contact-form me-lg-5 pe-lg-3" role="form">

                                <div class="form-floating">
                                    <input type="text" name="name" id="name" class="form-control" placeholder="Full name" required>

                                    <label for="name">Full name</label>
                                </div>

                                <div class="form-floating my-4">
                                    <input type="email" name="email" id="email" pattern="[^ @]*@[^ @]*" class="form-control" placeholder="Email address" required>

                                    <label for="email">Email address</label>
                                </div>
                                
                                <div class="form-floating my-4">
                                    <input type="subject" name="subject" id="subject"class="form-control" placeholder="Subject" required>

                                    <label for="subject">Subject</label>
                                </div>

                                <div class="form-floating mb-4">
                                    <textarea id="message" name="message" class="form-control" placeholder="Leave a comment here" required style="height: 160px"></textarea>

                                    <label for="message">Tell us about the project</label>
                                </div>

                                <div class="col-lg-5 col-6">
                                    <button type="submit" class="form-control">Send</button>
                                </div>
                            </form>
                        </div>

                        <div class="col-lg-6 col-12 mt-5 ms-auto">
                            <div class="row">
                                <div class="col-6 border-end contact-info">
                                    <h6 class="mb-3">New Business</h6>

                                    <a href="mailto:hello@company.com" class="custom-link">
                                        hello@company.com
                                        <i class="bi-arrow-right ms-2"></i>
                                    </a>
                                </div>

                                <div class="col-6 contact-info">
                                	<h6 class="mb-3">Main Studio</h6>

                                    <a href="mailto:studio@company.com" class="custom-link">
                                        studio@company.com
                                        <i class="bi-arrow-right ms-2"></i>
                                    </a>
                                </div>

                                <div class="col-6 border-top border-end contact-info">
                                    <h6 class="mb-3">Our Office</h6>

                                    <p class="text-muted">Akershusstranda 20, 0150 Oslo, Norway</p>
                                </div>

                                <div class="col-6 border-top contact-info">
                                    <h6 class="mb-3">Our Socials</h6>

                                    <ul class="social-icon">

                                        <li><a href="#" class="social-icon-link bi-messenger"></a></li>

                                        <li><a href="#" class="social-icon-link bi-youtube"></a></li>

                                        <li><a href="#" class="social-icon-link bi-instagram"></a></li>

                                        <li><a href="#" class="social-icon-link bi-whatsapp"></a></li>
                                    </ul>
                                </div>
                            </div>
                        </div>

                    </div>
                </div>
            </section>
        </main>

        <footer class="site-footer">
            <div class="container">
                <div class="row">

                    <div class="col-lg-3 col-10 me-auto mb-4">
                        <h4 class="text-white mb-3"><a href="index.html">Script</a> Genie</h4>
                        <p class="copyright-text text-muted mt-lg-5 mb-4 mb-lg-0">Copyright © 2024<strong>Script Genie</strong></p>
                        <br>
                        <p class="copyright-text">Designed by <a href="https://www.tooplate.com/" target="_blank">Tooplate</a></p>
                    </div>

                    <div class="col-lg-5 col-8">
                        <h5 class="text-white mb-3">Sitemap</h5>

                        <ul class="footer-menu d-flex flex-wrap">
                            <li class="footer-menu-item"><a href="about.html" class="footer-menu-link">Story</a></li>

                      

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">Privacy policy</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">FAQs</a></li>

                            <li class="footer-menu-item"><a href="#" class="footer-menu-link">Contact</a></li>
                        </ul>
                    </div>

                    <div class="col-lg-3 col-4">
                        <h5 class="text-white mb-3">Social</h5>

                        <ul class="social-icon">

                            <li><a href="#" class="social-icon-link bi-youtube"></a></li>

                            <li><a href="#" class="social-icon-link bi-whatsapp"></a></li>

                            <li><a href="#" class="social-icon-link bi-instagram"></a></li>

                            <li><a href="#" class="social-icon-link bi-skype"></a></li>
                        </ul>
                    </div>

                </div>
            </div>
        </footer>

        {% endblock %}

templates/index.html
{% extends "base.html" %}

{% load static %}
{%block content%}
{% if user.is_authenticated %}

    
    <section class="preloader">
        <div class="spinner">
            <span class="sk-inner-circle"></span>
        </div>
    </section>

    <main>

       

        <section class="slick-slideshow">   
            <div class="slick-custom">
                <img src="{% static 'images/slideshow/medium-shot-business-women-high-five.jpeg' %}" class="img-fluid" alt="">

                <div class="slick-bottom">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-6 col-10">
                                <h1 class="slick-title">Cool Fashion</h1>

                                <p class="lead text-white mt-lg-3 mb-lg-5">Little fashion template comes with total 8 HTML pages provided by Tooplate website.</p>

                                <a href="{% url 'about' %}" class="btn custom-btn">Learn more about us</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="slick-custom">
                <img src="{% static 'images/slideshow/team-meeting-renewable-energy-project.jpeg' %}" class="img-fluid" alt="">

                <div class="slick-bottom">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-6 col-10">
                                <h1 class="slick-title">New experience of inspiration</h1>

                                <p class="lead text-white mt-lg-3 mb-lg-5">Please share this site to your friends. Thank you for supporting us.</p>

                                <a href="{% url 'module:film_list' %}" class="btn custom-btn">Explore Films</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

            <div class="slick-custom">
                <img src="{% static 'images/slideshow/two-business-partners-working-together-office-computer.jpeg' %}" class="img-fluid" alt="">

                <div class="slick-bottom">
                    <div class="container">
                        <div class="row">
                            <div class="col-lg-6 col-10">
                                <h1 class="slick-title">Talk to us</h1>

                                <p class="lead text-white mt-lg-3 mb-lg-5">Tooplate is one of the best HTML CSS template websites for everyone.</p>

                                <a href="{% url 'contact' %}" class="btn custom-btn">Work with us</a>
                            </div>
                        </div>
                    </div>
                </div>
            </div>

        </section>
        <section class="about section-padding">
            <div class="container">
                <div class="row">
        
                    <div class="col-12 text-center">
                        <h2 class="mb-5">Get started with <span>Script</span> Genie</h2>
                    </div>
        
                    <div class="col-lg-2 col-12 mt-auto mb-auto">
                        <ul class="nav nav-pills mb-5 mx-auto justify-content-center align-items-center" id="pills-tab" role="tablist">
                            <li class="nav-item" role="presentation">
                                <button class="nav-link active" id="pills-home-tab" data-bs-toggle="pill" data-bs-target="#pills-home" type="button" role="tab" aria-controls="pills-home" aria-selected="true">Introduction</button>
                            </li>
        
                            <li class="nav-item" role="presentation">
                                <button class="nav-link" id="pills-youtube-tab" data-bs-toggle="pill" data-bs-target="#pills-youtube" type="button" role="tab" aria-controls="pills-youtube" aria-selected="true">How we work?</button>
                            </li>
        
                            <li class="nav-item" role="presentation">
                                <button class="nav-link" id="pills-skill-tab" data-bs-toggle="pill" data-bs-target="#pills-skill" type="button" role="tab" aria-controls="pills-skill" aria-selected="false">Capabilites</button>
                            </li>
                        </ul>
                    </div>
        
                    <div class="col-lg-10 col-12">
                        <div class="tab-content mt-2" id="pills-tabContent">
                            <div class="tab-pane fade show active" id="pills-home" role="tabpanel" aria-labelledby="pills-home-tab">
        
                                <div class="row">
                                    <div class="col-lg-7 col-12">
                                        <img src="{% static 'images/pim-chu-z6NZ76_UTDI-unsplash.jpeg' %}" class="img-fluid" alt="">
                                    </div>
        
                                    <div class="col-lg-5 col-12">
                                        <div class="d-flex flex-column h-100 ms-lg-4 mt-lg-0 mt-5">
                                            <h4 class="mb-3">Good <span>Design</span> <br>Ideas for <span>your</span> projects</h4>
        
                                            <p>Script Genie provides templates for modules like <strong>personnage</strong>, <strong>idée de film</strong>, <strong>projet</strong>, and <strong>effets visuels</strong>.</p>
        
                                            <p>As the template is based on Bootstrap 5 CSS, feel free to extend it with additional components as per your needs.</p>
        
                                            <div class="mt-2 mt-lg-auto">
                                                <a href="{% url 'about' %}" class="custom-link mb-2">
                                                    Learn more about us
                                                    <i class="bi-arrow-right ms-2"></i>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
        
                            <div class="tab-pane fade" id="pills-youtube" role="tabpanel" aria-labelledby="pills-youtube-tab">
        
                                <div class="row">
                                    <div class="col-lg-7 col-12">
                                        <div class="ratio ratio-16x9">
                                            <iframe src="https://www.youtube-nocookie.com/embed/f_7JqPDWhfw?controls=0" title="YouTube video player" frameborder="0" allow="accelerometer; autoplay; clipboard-write; encrypted-media; gyroscope; picture-in-picture" allowfullscreen></iframe>
                                        </div>
                                    </div>
        
                                    <div class="col-lg-5 col-12">
                                        <div class="d-flex flex-column h-100 ms-lg-4 mt-lg-0 mt-5">
                                            <h4 class="mb-3">Life at Studio</h4>
        
                                            <p>Over three years in business, We’ve had the chance to work on a variety of projects, with companies</p>
        
                                            <p>Custom work is branding, web design, UI/UX design</p>
        
                                            <div class="mt-2 mt-lg-auto">
                                                <a href="{% url 'contact' %}" class="custom-link mb-2">
                                                    Work with us
                                                    <i class="bi-arrow-right ms-2"></i>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
        
                            <div class="tab-pane fade" id="pills-skill" role="tabpanel" aria-labelledby="pills-skill-tab">
                                <div class="row">
                                    <div class="col-lg-7 col-12">
                                        <img src="{% static 'images/cody-lannom-G95AReIh_Ko-unsplash.jpeg' %}" class="img-fluid" alt="">
                                    </div>
        
                                    <div class="col-lg-5 col-12">
                                        <div class="d-flex flex-column h-100 ms-lg-4 mt-lg-0 mt-5">
                                            <h4 class="mb-3">What can help you?</h4>
        
                                            <p>Over three years in business, We’ve had the chance on projects</p>
        
                                            <div class="skill-thumb mt-3">
        
                                                <strong>Branding</strong>
                                                    <span class="float-end">90%</span>
                                                        <div class="progress">
                                                            <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="90" aria-valuemin="0" aria-valuemax="100" style="width: 90%;"></div>
                                                        </div>
        
                                                <strong>Design & Strategy</strong>
                                                    <span class="float-end">70%</span>
                                                        <div class="progress">
                                                            <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="70" aria-valuemin="0" aria-valuemax="100" style="width: 70%;"></div>
                                                        </div>
        
                                                <strong>Online Platform</strong>
                                                    <span class="float-end">80%</span>
                                                        <div class="progress">
                                                            <div class="progress-bar progress-bar-primary" role="progressbar" aria-valuenow="80" aria-valuemin="0" aria-valuemax="100" style="width: 80%;"></div>
                                                        </div>
        
                                            </div>
                                            
                                            <div class="mt-2 mt-lg-auto">
                                                <a href="{% url 'about' %}" class="custom-link mb-2">
                                                    Explore products
                                                    <i class="bi-arrow-right ms-2"></i>
                                                </a>
                                            </div>
                                        </div>
                                    </div>
                                </div>
                            </div>
        
                        </div>
                    </div>
        
                </div>
            </div>
        </section>
        
     

       

    </main>

    <footer class="site-footer">
        <div class="container">
            <div class="row">

                <div class="col-lg-3 col-10 me-auto mb-4">
                    <h4 class="text-white mb-3"><a href="index.html">Little</a> Fashion</h4>
                    <p class="copyright-text text-muted mt-lg-5 mb-4 mb-lg-0">Copyright © 2022 <strong>Little Fashion</strong></p>
                    <br>
                    <p class="copyright-text">Designed by <a href="https://www.tooplate.com/" target="_blank">Tooplate</a></p>
                </div>

                <div class="col-lg-5 col-8">
                    <h5 class="text-white mb-3">Sitemap</h5>

                    <ul class="footer-menu d-flex flex-wrap">
                        <li class="footer-menu-item"><a href="about.html" class="footer-menu-link">Story</a></li>

                        <li class="footer-menu-item"><a href="#" class="footer-menu-link">Products</a></li>

                        <li class="footer-menu-item"><a href="#" class="footer-menu-link">Privacy policy</a></li>

                        <li class="footer-menu-item"><a href="#" class="footer-menu-link">FAQs</a></li>

                        <li class="footer-menu-item"><a href="#" class="footer-menu-link">Contact</a></li>
                    </ul>
                </div>

                <div class="col-lg-3 col-4">
                    <h5 class="text-white mb-3">Social</h5>

                    <ul class="social-icon">

                        <li><a href="#" class="social-icon-link bi-youtube"></a></li>

                        <li><a href="#" class="social-icon-link bi-whatsapp"></a></li>

                        <li><a href="#" class="social-icon-link bi-instagram"></a></li>

                        <li><a href="#" class="social-icon-link bi-skype"></a></li>
                    </ul>
                </div>

            </div>
        </div>
    </footer>

{% else %}
<script>
    window.location.href = "http://127.0.0.1:8000/accounts/login/";
</script>
{% endif %}

     

{% endblock %}